// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDf5Kl7qcVpyg0V4VnnvGRIAVND2B8r1Y',
    appId: '1:462590622150:web:9ea88d17a1e6505d531ac7',
    messagingSenderId: '462590622150',
    projectId: 'handycrew-bd623',
    authDomain: 'handycrew-bd623.firebaseapp.com',
    databaseURL: 'https://handycrew-bd623-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'handycrew-bd623.appspot.com',
    measurementId: 'G-QMWF599Q10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Tw2dxFLAx2JORRDOmk7cLIpXi3_UYBI',
    appId: '1:462590622150:android:c08d7871571778db531ac7',
    messagingSenderId: '462590622150',
    projectId: 'handycrew-bd623',
    databaseURL: 'https://handycrew-bd623-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'handycrew-bd623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOE5yshDMIUVU9pfU5q3PLifdguACisLQ',
    appId: '1:462590622150:ios:29104b54f8f6d30e531ac7',
    messagingSenderId: '462590622150',
    projectId: 'handycrew-bd623',
    databaseURL: 'https://handycrew-bd623-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'handycrew-bd623.appspot.com',
    iosBundleId: 'com.example.handycrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOE5yshDMIUVU9pfU5q3PLifdguACisLQ',
    appId: '1:462590622150:ios:29104b54f8f6d30e531ac7',
    messagingSenderId: '462590622150',
    projectId: 'handycrew-bd623',
    databaseURL: 'https://handycrew-bd623-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'handycrew-bd623.appspot.com',
    iosBundleId: 'com.example.handycrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDf5Kl7qcVpyg0V4VnnvGRIAVND2B8r1Y',
    appId: '1:462590622150:web:6cda86546ff2c0b2531ac7',
    messagingSenderId: '462590622150',
    projectId: 'handycrew-bd623',
    authDomain: 'handycrew-bd623.firebaseapp.com',
    databaseURL: 'https://handycrew-bd623-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'handycrew-bd623.appspot.com',
    measurementId: 'G-3LLV7NV8JZ',
  );
}
